import type {
  NotificationPayload,
  NotificationTrigger,
  OwnerAlert,
  FreelanceChatSession,
  FreelanceInquiry,
} from "@/types/notifications";import { TRIGGER_CATEGORY } from "@/types/notifications";

export const DEMO_NOTIFICATIONS: NotificationPayload[] = [
  {
    id: "n1",
    trigger: "connection_accepted",
    category: "social",
    title: "Sarah Chen accepted your connection",
    titleAr: "قبلت Sarah Chen طلب التواصل",
    body: "You are now connected on VORA Network.",
    bodyAr: "أصبحتم متصلين على شبكة VORA.",
    href: "/network/profile/sarah-chen",
    isRead: false,
    isCritical: false,
    createdAt: "2026-07-17T03:55:00Z",
    channels: ["in_app", "push"],
  },
  {
    id: "n2",
    trigger: "post_mention",
    category: "social",
    title: "Mohammed mentioned you in a post",
    titleAr: "Mohammed أشار إليك في منشور",
    body: '"Great insights on design systems, @alex-morgan!"',
    href: "/network",
    isRead: false,
    isCritical: false,
    createdAt: "2026-07-17T03:30:00Z",
    channels: ["in_app", "push"],
  },
  {
    id: "n3",
    trigger: "application_status_change",
    category: "employment",
    title: "Moved to Interview Phase",
    titleAr: "تم نقلك إلى مرحلة المقابلة",
    body: "TechCorp Global moved your application for Senior Product Designer to Interview Scheduled.",
    bodyAr: "TechCorp Global نقلت طلبك لوظيفة Senior Product Designer إلى مرحلة المقابلة.",
    href: "/network/jobs",
    isRead: false,
    isCritical: false,
    createdAt: "2026-07-17T02:00:00Z",
    channels: ["in_app", "email", "push"],
  },
  {
    id: "n4",
    trigger: "new_order",
    category: "financial",
    title: "New order received",
    titleAr: "طلب جديد",
    body: "Order VORA-2026-7842 — Professional Logo Design (SR 449)",
    bodyAr: "طلب VORA-2026-7842 — تصميم شعار احترافي (449 ر.س)",
    href: "/freelance/orders/ord-1",
    amountSar: 449,
    isRead: true,
    isCritical: false,
    createdAt: "2026-07-15T10:01:00Z",
    channels: ["in_app", "email", "push"],
  },
  {
    id: "n5",
    trigger: "work_delivered",
    category: "financial",
    title: "Work delivered for your review",
    titleAr: "تم تسليم العمل للمراجعة",
    body: "Alex Design Studio delivered final work for Order VORA-2026-7842.",
    href: "/freelance/orders/ord-1",
    isRead: true,
    isCritical: false,
    createdAt: "2026-07-15T16:00:00Z",
    channels: ["in_app", "push"],
  },
];

export const DEMO_OWNER_ALERTS: OwnerAlert[] = [
  {
    id: "oa1",
    trigger: "subscription_payment",
    category: "financial",
    title: "New Premium Subscription",
    body: "Sarah Chen subscribed to Premium Yearly — SR 120",
    amountSar: 120,
    isRead: false,
    isCritical: true,
    createdAt: "2026-07-17T03:50:00Z",
    channels: ["in_app", "email", "push"],
  },
  {
    id: "oa2",
    trigger: "withdrawal_request",
    category: "financial",
    title: "New Withdrawal Request",
    body: "Alex Morgan requested SR 2,500 transfer to Al Rajhi Bank (IBAN ending 7519)",
    amountSar: 2500,
    href: "/admin/finance",
    isRead: false,
    isCritical: true,
    createdAt: "2026-07-16T14:00:00Z",
    channels: ["in_app", "email"],
  },
  {
    id: "oa3",
    trigger: "failed_login",
    category: "security",
    title: "Failed Login Attempts Detected",
    body: "5 failed attempts on admin@vora.sa from Tor exit node IP",
    href: "/admin/security",
    isRead: false,
    isCritical: true,
    createdAt: "2026-07-17T02:15:00Z",
    channels: ["in_app", "email", "push"],
  },
  {
    id: "oa4",
    trigger: "dispute_filed",
    category: "financial",
    title: "Dispute Ticket Opened",
    body: "Order VORA-2026-9102 — SR 899 escrow frozen. Urgent review required.",
    amountSar: 899,
    href: "/admin/disputes/disp-1",
    isRead: false,
    isCritical: true,
    createdAt: "2026-07-16T18:30:00Z",
    channels: ["in_app", "email"],
  },
];

export const DEMO_FREELANCE_CHATS: FreelanceChatSession[] = [
  {
    id: "fc1",
    orderId: "ord-1",
    orderNumber: "VORA-2026-7842",
    orderStatus: "in_progress",
    buyerName: "Fatima Al-Qahtani",
    sellerName: "Alex Morgan",
    isUnlocked: true,
    unlockReason: "escrow_paid",
    lastMessage: "Requirements submitted. Starting work now.",
    lastMessageAt: "2026-07-15T14:30:00Z",
    unreadCount: 1,
  },
  {
    id: "fc2",
    buyerName: "Omar Hassan",
    sellerName: "Alex Morgan",
    isUnlocked: false,
    unlockReason: "locked",
    lastMessage: "",
    lastMessageAt: "2026-07-16T09:00:00Z",
    unreadCount: 0,
  },
];

export const DEMO_INQUIRIES: FreelanceInquiry[] = [
  {
    id: "inq1",
    buyerName: "Omar Hassan",
    serviceTitle: "UI/UX App Design",
    message: "Hi, I need a fintech app design. Can you share your portfolio?",
    status: "pending",
    createdAt: "2026-07-16T09:00:00Z",
  },
];

export function buildNotification(
  trigger: NotificationTrigger,
  title: string,
  body: string,
  opts?: Partial<NotificationPayload>
): NotificationPayload {
  return {
    id: `notif-${Date.now()}`,
    trigger,
    category: TRIGGER_CATEGORY[trigger],
    title,
    body,
    isRead: false,
    isCritical: opts?.isCritical ?? false,
    createdAt: new Date().toISOString(),
    channels: opts?.channels ?? ["in_app"],
    ...opts,
  };
}
