import type { NavigationLinkRecord } from "@/types/navigation";

/** Default sidebar links when Supabase is unavailable */
export const FALLBACK_NAVIGATION_LINKS: NavigationLinkRecord[] = [
  {
    id: "fallback-network-home",
    platform: "network",
    placement: "sidebar",
    labelKey: "nav.home",
    labelEn: "Home",
    labelAr: "الرئيسية",
    href: "/network",
    icon: "🏠",
    sortOrder: 10,
    requiresAuth: false,
    minRole: null,
    isActive: true,
  },
  {
    id: "fallback-network-profile",
    platform: "network",
    placement: "sidebar",
    labelKey: "nav.profile",
    labelEn: "Profile",
    labelAr: "الملف الشخصي",
    href: "/profile/me",
    icon: "👤",
    sortOrder: 20,
    requiresAuth: false,
    minRole: null,
    isActive: true,
  },
  {
    id: "fallback-network-messages",
    platform: "network",
    placement: "sidebar",
    labelKey: "nav.messaging",
    labelEn: "Messaging",
    labelAr: "الرسائل",
    href: "/network/messages",
    icon: "💬",
    sortOrder: 30,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-network-jobs",
    platform: "network",
    placement: "sidebar",
    labelKey: "nav.jobs",
    labelEn: "Jobs",
    labelAr: "الوظائف",
    href: "/network/jobs",
    icon: "💼",
    sortOrder: 40,
    requiresAuth: false,
    minRole: null,
    isActive: true,
  },
  {
    id: "fallback-network-ai",
    platform: "network",
    placement: "sidebar",
    labelKey: "nav.voraAi",
    labelEn: "VORA AI",
    labelAr: "VORA AI",
    href: "/network/ai",
    icon: "✨",
    sortOrder: 50,
    requiresAuth: true,
    minRole: "professional",
    isActive: true,
  },
  {
    id: "fallback-freelance-home",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.home",
    labelEn: "Marketplace",
    labelAr: "السوق",
    href: "/freelance",
    icon: "🏠",
    sortOrder: 10,
    requiresAuth: false,
    minRole: null,
    isActive: true,
  },
  {
    id: "fallback-freelance-search",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.search",
    labelEn: "Search",
    labelAr: "بحث",
    href: "/freelance/search",
    icon: "🔍",
    sortOrder: 20,
    requiresAuth: false,
    minRole: null,
    isActive: true,
  },
  {
    id: "fallback-freelance-messages",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.messages",
    labelEn: "Messages",
    labelAr: "الرسائل",
    href: "/freelance/messages",
    icon: "💬",
    sortOrder: 30,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-dashboard",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.dashboard",
    labelEn: "My Store",
    labelAr: "متجري",
    href: "/freelance/dashboard",
    icon: "🛍️",
    sortOrder: 40,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-my-services",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.myServices",
    labelEn: "My Services",
    labelAr: "خدماتي",
    href: "/freelance/manage-store?section=services",
    icon: "📋",
    sortOrder: 41,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-orders",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.orders",
    labelEn: "Orders",
    labelAr: "الطلبات",
    href: "/freelance/orders",
    icon: "📦",
    sortOrder: 50,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-edit-profile",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "profile.header.editProfile",
    labelEn: "Edit Profile",
    labelAr: "تعديل الملف",
    href: "/network/settings/profile",
    icon: "✏️",
    sortOrder: 55,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-billing",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "billing.nav.billingLabel",
    labelEn: "Billing",
    labelAr: "الفواتير",
    href: "/billing/wallet",
    icon: "💳",
    sortOrder: 56,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-view-store",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.myStore",
    labelEn: "View My Store",
    labelAr: "عرض متجري",
    href: "/freelance/store/{storeSlug}",
    icon: "🛒",
    sortOrder: 57,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-edit-store",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "storeEdit.editStore",
    labelEn: "Edit Store",
    labelAr: "تعديل المتجر",
    href: "/freelance/store/{storeSlug}/edit",
    icon: "📝",
    sortOrder: 58,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-freelance-manage-store",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.createManageStore",
    labelEn: "Create / Manage Store",
    labelAr: "إنشاء / إدارة المتجر",
    href: "/freelance/manage-store",
    icon: "⚙️",
    sortOrder: 59,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "fallback-network-settings",
    platform: "network",
    placement: "sidebar",
    labelKey: "nav.settings",
    labelEn: "Settings",
    labelAr: "الإعدادات",
    href: "/network/settings",
    icon: "⚙️",
    sortOrder: 60,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
];
