import type { NavigationLinkRecord } from "@/types/navigation";

/**
 * Canonical Network (Work) sidebar — dual-identity standard.
 */
export const NETWORK_SIDEBAR_LINKS: NavigationLinkRecord[] = [
  {
    id: "network-feed",
    platform: "network",
    placement: "sidebar",
    labelKey: "sidebar.network.feed",
    labelEn: "Feed",
    labelAr: "الموجز",
    href: "/network",
    icon: "🏠",
    sortOrder: 10,
    requiresAuth: false,
    minRole: null,
    isActive: true,
  },
  {
    id: "network-connections",
    platform: "network",
    placement: "sidebar",
    labelKey: "sidebar.network.connections",
    labelEn: "Connection Management",
    labelAr: "إدارة الاتصالات",
    href: "/network/connections",
    icon: "🤝",
    sortOrder: 20,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "network-profile-mgmt",
    platform: "network",
    placement: "sidebar",
    labelKey: "sidebar.network.profileManagement",
    labelEn: "Profile Management",
    labelAr: "إدارة الملف الشخصي",
    href: "/network/settings/profile",
    icon: "👤",
    sortOrder: 30,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "network-messages",
    platform: "network",
    placement: "sidebar",
    labelKey: "sidebar.network.personalMessages",
    labelEn: "Personal Messages",
    labelAr: "الرسائل الشخصية",
    href: "/network/messages",
    icon: "💬",
    sortOrder: 40,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "network-settings",
    platform: "network",
    placement: "sidebar",
    labelKey: "sidebar.network.settings",
    labelEn: "Network Settings",
    labelAr: "إعدادات الشبكة",
    href: "/network/settings",
    icon: "⚙️",
    sortOrder: 50,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "network-professional-tools",
    platform: "network",
    placement: "sidebar",
    labelKey: "sidebar.network.professionalTools",
    labelEn: "Professional Tools",
    labelAr: "الأدوات المهنية",
    href: "/network/ai",
    icon: "✨",
    sortOrder: 60,
    requiresAuth: true,
    minRole: "professional",
    isActive: true,
  },
  {
    id: "network-billing",
    platform: "network",
    placement: "sidebar",
    labelKey: "sidebar.network.personalBilling",
    labelEn: "Personal Billing",
    labelAr: "الفواتير الشخصية",
    href: "/billing/wallet",
    icon: "💳",
    sortOrder: 70,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
];

/**
 * Canonical Freelance sidebar — dual-identity standard.
 * Routes using {storeSlug} are resolved per-user; unresolved links are hidden.
 */
export const FREELANCE_SIDEBAR_LINKS: NavigationLinkRecord[] = [
  {
    id: "freelance-store-management",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.createManageStore",
    labelEn: "Create / Manage Store",
    labelAr: "إنشاء / إدارة المتجر",
    href: "/freelance/store/{storeSlug}/manage",
    icon: "⚙️",
    sortOrder: 10,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-store-profile",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.storeProfile",
    labelEn: "Store Profile",
    labelAr: "ملف المتجر",
    href: "/freelance/store/{storeSlug}/edit",
    icon: "📝",
    sortOrder: 20,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-store-media",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.storeMedia",
    labelEn: "Store Media",
    labelAr: "وسائط المتجر",
    href: "/freelance/store/{storeSlug}/edit?section=media",
    icon: "🖼️",
    sortOrder: 30,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-advanced-dashboard",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.advancedDashboard",
    labelEn: "Advanced Dashboard",
    labelAr: "لوحة التحكم المتقدمة",
    href: "/freelance/dashboard",
    icon: "📊",
    sortOrder: 40,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-my-services",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.myServices",
    labelEn: "My Services",
    labelAr: "خدماتي",
    href: "/freelance/store/{storeSlug}/manage?section=services",
    icon: "📋",
    sortOrder: 45,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-orders",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.orders",
    labelEn: "Orders",
    labelAr: "الطلبات",
    href: "/freelance/orders",
    icon: "📦",
    sortOrder: 50,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-wallet",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.walletBilling",
    labelEn: "Wallet / Billing",
    labelAr: "المحفظة / الفواتير",
    href: "/billing/wallet",
    icon: "💳",
    sortOrder: 60,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-messages",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.storeMessages",
    labelEn: "Store Messages",
    labelAr: "رسائل المتجر",
    href: "/freelance/messages",
    icon: "💬",
    sortOrder: 70,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-products",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.productManagement",
    labelEn: "Product Management",
    labelAr: "إدارة المنتجات",
    href: "/freelance/store/{storeSlug}/manage?section=products",
    icon: "🛍️",
    sortOrder: 80,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-analytics",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.analytics",
    labelEn: "Analytics",
    labelAr: "التحليلات",
    href: "/freelance/dashboard?section=analytics",
    icon: "📈",
    sortOrder: 90,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-settings",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.settings",
    labelEn: "Settings",
    labelAr: "الإعدادات",
    href: "/freelance/store/{storeSlug}/edit?section=settings",
    icon: "🔧",
    sortOrder: 100,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
  {
    id: "freelance-view-store",
    platform: "freelance",
    placement: "sidebar",
    labelKey: "sidebar.freelance.myStore",
    labelEn: "View My Store",
    labelAr: "عرض متجري",
    href: "/freelance/store/{storeSlug}",
    icon: "🛒",
    sortOrder: 110,
    requiresAuth: true,
    minRole: "registered",
    isActive: true,
  },
];
